using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Forms=System.Windows.Forms;
using Application=System.Windows.Application;
using Button=System.Windows.Controls.Button;
using CheckBox=System.Windows.Controls.CheckBox;
using ComboBox=System.Windows.Controls.ComboBox;
using Image=System.Windows.Controls.Image;
using TextBox=System.Windows.Controls.TextBox;
using MessageBox=System.Windows.MessageBox;
namespace WakeRemote;
public partial class MainWindow:Window {
    readonly Forms.NotifyIcon tray; Enrollment? enrollment; byte[]? key; System.Windows.Controls.ComboBox? targets; TextBlock? statusTitle,statusDetail;
    static readonly System.Windows.Media.Brush White=B("#FFFFFF"),Muted=B("#929292"),Blue=B("#26A7E1"),Surface=B("#181818"),Border=B("#262626"); static System.Windows.Media.Brush B(string c)=>new BrushConverter().ConvertFromString(c) as System.Windows.Media.Brush??System.Windows.Media.Brushes.White;
    public MainWindow(){InitializeComponent();tray=new Forms.NotifyIcon{Icon=new System.Drawing.Icon("Assets/app.ico"),Text="Wake Remote",Visible=true};var menu=new Forms.ContextMenuStrip();menu.Items.Add("Wake",null,async(_,_)=>await Dispatcher.InvokeAsync(Wake));menu.Items.Add("Open",null,(_,_)=>Dispatcher.Invoke(()=>{Show();WindowState=WindowState.Normal;Activate();}));menu.Items.Add("Exit",null,(_,_)=>Dispatcher.Invoke(()=>{tray.Visible=false;Application.Current.Shutdown();}));tray.ContextMenuStrip=menu;tray.DoubleClick+=(_,_)=>Dispatcher.Invoke(()=>{Show();Activate();});Closing+=(s,e)=>{e.Cancel=true;Hide();};LoadEnrollment();ShowHome();}
    void LoadEnrollment(){try{if(SecureStore.Exists)(enrollment,key)=SecureStore.Load();}catch{SecureStore.Clear();enrollment=null;key=null;}}
    StackPanel Base(){Content.Children.Clear();var p=new StackPanel();Content.Children.Add(p);return p;}
    TextBlock Text(string value,double size,System.Windows.Media.Brush brush,FontWeight? weight=null)=>new(){Text=value,FontSize=size,Foreground=brush,FontWeight=weight??FontWeights.Normal,TextWrapping=TextWrapping.Wrap,TextAlignment=TextAlignment.Center,Margin=new Thickness(0,0,0,8)};
    System.Windows.Controls.Button Primary(string label){return new System.Windows.Controls.Button{Content=label,Style=(Style)FindResource("PrimaryButton"),Margin=new Thickness(0,8,0,0)};}
    Border Status(string title,string detail){statusTitle=Text(title,17,White,FontWeights.Bold);statusTitle.TextAlignment=TextAlignment.Left;statusDetail=Text(detail,14,Muted);statusDetail.TextAlignment=TextAlignment.Left;var stack=new StackPanel{Margin=new Thickness(18)};stack.Children.Add(statusTitle);stack.Children.Add(statusDetail);return new Border{MinHeight=104,Background=Surface,BorderBrush=Border,BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(16),Child=stack,Margin=new Thickness(0,8,0,8)};}
    void ShowHome(){BackButton.Visibility=Visibility.Hidden;SettingsButton.Visibility=Visibility.Visible;var p=Base();p.Children.Add(new Image{Source=new BitmapImage(new Uri("Assets/icon.png",UriKind.Relative)),Width=128,Height=128,Stretch=Stretch.Uniform,Margin=new Thickness(0,0,0,16)});p.Children.Add(Text("Wake your computer",34,White,FontWeights.Bold));p.Children.Add(Text("Securely send a wake signal from anywhere.",15,Muted));p.Children.Add(Status(enrollment is null?"Setup required":"Ready",enrollment is null?"Enroll this device to continue.":"Secure key installed."));if(enrollment?.Targets.Count>1){targets=new ComboBox{ItemsSource=enrollment.Targets,DisplayMemberPath="Label",SelectedIndex=0,Height=48,Margin=new Thickness(0,0,0,8)};p.Children.Add(targets);}var button=Primary(enrollment is null?"Enroll device":"Wake computer");button.Click+=enrollment is null?(_,_)=>ShowEnroll():async(_,_)=>await Wake();p.Children.Add(button);}
    void ShowEnroll(){BackButton.Visibility=Visibility.Visible;SettingsButton.Visibility=Visibility.Hidden;var p=Base();p.Children.Add(new Image{Source=new BitmapImage(new Uri("Assets/icon.png",UriKind.Relative)),Width=128,Height=128,Stretch=Stretch.Uniform});p.Children.Add(Text("Connect Wake Remote",30,White,FontWeights.Bold));p.Children.Add(Text("Paste the single-use enrollment link, or enter the 64-character key manually.",14,Muted));var input=new TextBox{ToolTip="wakeremote://enroll?... or 64 hexadecimal characters",Margin=new Thickness(0,16,0,8)};p.Children.Add(input);var note=Text("Webcam QR scanning is not available on this device. Paste the link from any QR scanner.",12,Muted);p.Children.Add(note);p.Children.Add(Status("Secure enrollment","Your key is protected with Windows DPAPI for this user."));var button=Primary("Enroll securely");button.Click+=async(_,_)=>{try{button.IsEnabled=false;if(System.Text.RegularExpressions.Regex.IsMatch(input.Text.Trim(),"^[0-9a-fA-F]{64}$")){var raw=Convert.FromHexString(input.Text.Trim());var manual=new Enrollment("main","https://wol.apextechlabs.com",new(){new("main-pc","Main PC")});SecureStore.Save(manual,raw);}else{var result=await WakeClient.EnrollAsync(input.Text.Trim());SecureStore.Save(result.enrollment,result.key);}LoadEnrollment();ShowHome();}catch(Exception ex){statusTitle!.Text="Enrollment failed";statusDetail!.Text=ex.Message;button.IsEnabled=true;}};p.Children.Add(button);}
    void ShowSettings(){BackButton.Visibility=Visibility.Visible;SettingsButton.Visibility=Visibility.Hidden;var p=Base();p.Children.Add(Text("Settings",34,White,FontWeights.Bold));p.Children.Add(Text(enrollment is null?"Not enrolled":$"{enrollment.ServerUrl}\n{string.Join(", ",enrollment.Targets.Select(t=>t.Label))}",14,Muted));var launch=new CheckBox{Content="Launch at login",Foreground=White,Margin=new Thickness(0,24,0,8),IsChecked=LoginStartup.Enabled};launch.Checked+=(_,_)=>LoginStartup.Enabled=true;launch.Unchecked+=(_,_)=>LoginStartup.Enabled=false;p.Children.Add(launch);p.Children.Add(Text("Global hotkey: Ctrl+Alt+W",13,Muted));var remove=new Button{Content="Remove secure key",Height=48,Background=B("#7B2929"),Foreground=White,BorderThickness=new Thickness(0),Margin=new Thickness(0,32,0,0)};remove.Click+=(_,_)=>{if(MessageBox.Show("Remove this user’s secure enrollment?","Wake Remote",MessageBoxButton.YesNo,MessageBoxImage.Warning)==MessageBoxResult.Yes){SecureStore.Clear();LoadEnrollment();ShowHome();}};p.Children.Add(remove);}
    async Task Wake(){if(enrollment is null||key is null){ShowEnroll();return;}var alias=(targets?.SelectedItem as Target)?.Alias??enrollment.Targets[0].Alias;statusTitle!.Text="Sending securely";statusDetail!.Text="Creating a fresh signed request…";var result=await WakeClient.WakeAsync(enrollment,key,alias);statusTitle.Text=result.Title;statusDetail.Text=result.Detail;tray.ShowBalloonTip(3000,result.Title,result.Detail,result.Success?Forms.ToolTipIcon.Info:Forms.ToolTipIcon.Warning);}
    void Back_Click(object s,RoutedEventArgs e)=>ShowHome();void Settings_Click(object s,RoutedEventArgs e)=>ShowSettings();
    protected override void OnSourceInitialized(EventArgs e){base.OnSourceInitialized(e);var source=HwndSource.FromHwnd(new WindowInteropHelper(this).Handle);source.AddHook((IntPtr h,int m,IntPtr w,IntPtr l,ref bool handled)=>{if(m==0x0312&&w.ToInt32()==9001){_ = Wake();handled=true;}return IntPtr.Zero;});RegisterHotKey(source.Handle,9001,0x0002|0x0001,0x57);}
    [DllImport("user32.dll")]static extern bool RegisterHotKey(IntPtr hWnd,int id,uint fsModifiers,uint vk);
}
static class LoginStartup{const string Path=@"Software\Microsoft\Windows\CurrentVersion\Run";public static bool Enabled{get{using var k=Microsoft.Win32.Registry.CurrentUser.OpenSubKey(Path);return k?.GetValue("WakeRemote")!=null;}set{using var k=Microsoft.Win32.Registry.CurrentUser.CreateSubKey(Path);if(value)k.SetValue("WakeRemote",$"\"{Environment.ProcessPath}\"");else k.DeleteValue("WakeRemote",false);}}}
