import {useEffect,useRef,useState} from 'react'; import {createRoot} from 'react-dom/client'; import {registerSW} from 'virtual:pwa-register';
import {clearEnrollment,loadEnrollment,saveEnrollment} from './storage'; import {importKey,parseEnrollmentUri,signRequest,validateKey} from './protocol'; import './styles.css'; import './responsive.css';
registerSW({immediate:true});
const blank={key:null,keyId:'main',serverUrl:'',targets:[]};
function Footer(){return <footer><img src="/apex-shield.webp" alt=""/> Apex Tech Labs</footer>}
function Header({screen,setScreen}){return <header><button className="nav" onClick={()=>setScreen('home')} aria-label="Back" disabled={screen==='home'}>{screen==='home'?'':'‹ Back'}</button><span>Wake Remote</span><button className="nav" onClick={()=>setScreen('settings')}>{screen==='settings'?'':'Settings'}</button></header>}
function Status({state,detail}){return <section className={`status ${state}`} aria-live="polite"><i></i><div><strong>{state==='sent'?'Wake signal sent':state==='sending'?'Sending securely':state==='error'?'Request not sent':state==='ready'?'Ready':'Setup required'}</strong><p>{detail}</p></div></section>}
function Scanner({onScan,onClose}){const video=useRef();useEffect(()=>{let stream,timer;(async()=>{if(!('BarcodeDetector'in window))return;stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});video.current.srcObject=stream;const detector=new BarcodeDetector({formats:['qr_code']});timer=setInterval(async()=>{const [code]=await detector.detect(video.current);if(code)onScan(code.rawValue)},300)})().catch(()=>{});return()=>{clearInterval(timer);stream?.getTracks().forEach(t=>t.stop())}},[onScan]);return <div className="modal"><div><h2>Scan enrollment QR</h2>{'BarcodeDetector'in window?<video ref={video} autoPlay playsInline/>:<p>QR scanning is unavailable in this browser. Paste the enrollment link instead.</p>}<button className="secondary" onClick={onClose}>Cancel</button></div></div>}
function App(){const [data,setData]=useState(blank),[screen,setScreen]=useState('home'),[status,setStatus]=useState(['setup','Enroll this device to continue.']),[target,setTarget]=useState(''),[input,setInput]=useState(''),[manualServer]=useState('https://wol.apextechlabs.com'),[mode,setMode]=useState('link'),[scan,setScan]=useState(false),[allowHttp,setAllowHttp]=useState(false);
useEffect(()=>{loadEnrollment().then(d=>{if(d.key){setData(d);setTarget(d.targets?.[0]?.alias||'');setStatus(['ready','Secure key installed.'])}})},[]);
async function enroll(value=input){try{let next;if(mode==='link'||value.startsWith('wakeremote://')){const e=parseEnrollmentUri(value,allowHttp);const response=await fetch(`${e.serverUrl}/v1/enroll`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:e.token})});if(!response.ok)throw new Error(response.status===401?'This enrollment link is expired or already used.':'Enrollment failed.');const payload=await response.json();next={keyId:payload.key_id,serverUrl:payload.server_url,targets:payload.targets};next.key=await importKey(payload.key)}else{if(!validateKey(value))throw new Error('Enter exactly 64 hexadecimal characters.');const origin=new URL(manualServer);if(origin.protocol!=='https:'&&!(allowHttp&&origin.protocol==='http:'))throw new Error('Server URL must use HTTPS.');next={keyId:'main',serverUrl:origin.origin,targets:[{alias:'main-pc',label:'Main PC'}],key:await importKey(value)}}await saveEnrollment({keyId:next.keyId,serverUrl:next.serverUrl,targets:next.targets},next.key);setData(next);setTarget(next.targets[0].alias);setInput('');setStatus(['ready','Enrollment complete.']);setScreen('home')}catch(e){setStatus(['error',e.message])}}
async function wake(){setStatus(['sending','Creating a fresh signed request…']);try{const signed=await signRequest(data.key,target);const response=await fetch(`${data.serverUrl}/v1/wake`,{method:'POST',headers:signed.headers,body:signed.body});const messages={401:'Authentication failed. Check the key and device clock.',404:'The selected target is not configured.',429:'Too many attempts. Wait a minute.',503:'The server could not reach the target network.'};if(response.status===204)setStatus(['sent','Your computer may take a moment to come online.']);else setStatus(['error',messages[response.status]||`Unexpected server response (${response.status}).`])}catch{setStatus(['error','Network unavailable. Check your connection and try again.'])}}
async function remove(){if(confirm('Remove this device’s secure enrollment?')){await clearEnrollment();setData(blank);setStatus(['setup','Enroll this device to continue.']);setScreen('home')}}
return <div className="app"><Header screen={screen} setScreen={setScreen}/><main>{screen==='home'?<><img className="logo" src="/icon.webp" alt="Wake Remote"/><div className="copy"><h1>Wake your computer</h1><p>Securely send a wake signal from anywhere.</p></div><Status state={status[0]} detail={status[1]}/>{data.targets?.length>1&&<label>Target<select value={target} onChange={e=>setTarget(e.target.value)}>{data.targets.map(t=><option key={t.alias} value={t.alias}>{t.label}</option>)}</select></label>}<button className="primary" onClick={data.key?wake:()=>setScreen('enroll')} disabled={status[0]==='sending'}>{data.key?'Wake computer':'Enroll device'}</button></>:screen==='enroll'?<><img className="logo small" src="/icon.webp" alt="Wake Remote"/><div className="copy"><h1>Connect Wake Remote</h1><p>Scan the single-use server QR or use the manual fallback.</p></div><div className="tabs"><button onClick={()=>setMode('link')} aria-pressed={mode==='link'}>Enrollment link</button><button onClick={()=>setMode('key')} aria-pressed={mode==='key'}>Manual key</button></div><button className="secondary" onClick={()=>setScan(true)}>Scan QR code</button><label>{mode==='link'?'Enrollment link':'64-character HMAC key'}<input type="password" value={input} onChange={e=>setInput(e.target.value)} placeholder={mode==='link'?'wakeremote://enroll?...':'64 hexadecimal characters'} aria-invalid={mode==='key'&&input.length>0&&!validateKey(input)}/></label>{mode==='link'&&<label className="check"><input type="checkbox" checked={allowHttp} onChange={e=>setAllowHttp(e.target.checked)}/> Allow plaintext HTTP on this LAN</label>}<Status state={status[0]} detail={status[1]}/><button className="primary" onClick={()=>enroll()}>Enroll securely</button></>:<><div className="copy settings"><h1>Settings</h1><p>{data.serverUrl||'Not enrolled'} · {target||'No target'}</p></div><section className="danger"><h2>Remove enrollment</h2><p>This browser will no longer be able to send wake requests.</p><button onClick={remove}>Remove secure key</button></section></>}</main><Footer/>{scan&&<Scanner onScan={v=>{setScan(false);setInput(v);setMode('link');enroll(v)}} onClose={()=>setScan(false)}/>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
